apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: my-k3d-cluster
servers: 1
agents: 1
image: rancher/k3s:v1.27.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  # - port: 443:443
  #   nodeFilters:
  #     - loadbalancer
